### PR TITLE
Switch to native clipboard API (close #2386)

### LINKED ISSUE #2386: UI Crash on Copying Image Attachments
**Prerequisites**

affected version:
Latest
make sure to check this before filing an issue:

- [x] I am running the latest version
- [x] I checked to make sure that this issue has not already been filed

**Describe the issue**

The UI crashes and turns into a white screen, when the user clicks on the copy button on an image attachment preview. This crashe doesn't happen on copying the content of a text attachment.

**Steps to Reproduce**

* Open a DLT File with attachment
* Select an image attachment (PNG image in my case)
* Click on the copy button on the top right corner of the image preview on the left bottom of Chipmunk Window.

**Environment**

Linux Ubuntu 22.04

### PR DESCRIPTION
**Pull request by DmitryAstafyev**
## Changes
- Extend exposed API with clipboard API
- Switch from browser's clipboard API to native one (in context of images)
- Switch loading of attachment to stream-based

### CODE REVIEW

File: application/client/src/app/ui/views/sidebar/attachments/preview/image/component.ts [hunk 1]
```diff
@@ -206,12 +206,16 @@ export class Preview extends ChangesDetector implements AfterViewInit, AfterCont
...
-                            [response.type]: response,
-                        }),
-                    ])
+                response
+                    .arrayBuffer()
+                    .then((buffer) => {
+                        // We are using native clipboard API, but not browser one (navigator.clipboard)
+                        // to avoid possible issues with size of blob.
+                        window.electron.clipboard.write(
+                            response.type || 'application/octet-stream',
```
Comment (AmmarAbouZor) [inline application/client/src/app/ui/views/sidebar/attachments/preview/image/component.ts:215]: Would it be clearer and more javascript like to use `??` instead of `||`?

File: application/holder/src/service/electron/handles/clipboard.ts [hunk 2]
```diff
@@ -0,0 +1,26 @@
...
+        if (mime.startsWith('image/')) {
+            const img = nativeImage.createFromBuffer(buf);
+            clipboard.writeImage(img);
+            return;
+        }
+        if (mime.startsWith('text/')) {
+            clipboard.writeText(buf.toString('utf8'));
+            return;
+        }
+        clipboard.writeBuffer(mime || 'application/octet-stream', buf);
```
Comment (AmmarAbouZor) [inline application/holder/src/service/electron/handles/clipboard.ts:23]: Same remark about `??` and `||`

**Review by AmmarAbouZor — APPROVED** [review]
Thanks @DmitryAstafyev for the fix and the great documentation :pray: 

I have one remark regarding using `||` and if it would be more suitable to use `??` instead.
This is tiny suggestion only and you can merge this PR with any further review from my side regardless which one to you will choose
